# Generated by Django 5.2.1 on 2025-06-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('leguminosa', 'Leguminosa'), ('hortaliça', 'Hortaliça'), ('fruta', ' Fruta')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('Data_Do_Plantio', models.CharField(max_length=100)),
                ('Adubo', models.CharField(max_length=100)),
                ('Fase', models.CharField(max_length=100)),
                ('Observacao', models.TextField(blank=True)),
            ],
        ),
    ]
